spring:
  profiles:
    include: oauth
  jpa:
    show_sql: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

kakao:
  url:
    auth: https://kauth.kakao.com/
    api: https://kapi.kakao.com/


jwt:
  secret: luke-local
  expiration: 1480000
  header: Authorization