spring:
  profiles:
    include: oauth2
  jpa:
    show_sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console