spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

kakao:
  client_id: test
  client_secret: test
  url:
    auth: https://kauth.kakao.com/
    api: https://kapi.kakao.com/


jwt:
  expiration: 100
  header: user_id
  secret: test